version: '3'

services:
  ai-gateway:
    container_name: ai-gateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
    - ./:/code
    env_file:
    - .env
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]